In [1]:
# %pip install azureml-dataset-runtime --upgrade

In [2]:
from azureml.core import Workspace, Datastore, Dataset
import pandas as pd

ws = Workspace.from_config()

adls = Datastore.get(ws, "olistmldatastore")

dataset = Dataset.File.from_files(
    path=(adls, "gold/")
)

mount = dataset.mount()
mount.start()
df = pd.read_parquet(f"{mount.mount_point}")

In [3]:
df.shape

(115038, 37)

In [4]:
pd.set_option("display.max_columns", None)   # show all columns
pd.set_option("display.max_colwidth", None)

In [5]:
df.head()

,product_category_name,seller_id,product_id,order_id,customer_id,order_status,order_purchase_timestamp,order_approved_at,order_delivered_carrier_date,order_delivered_customer_date,order_estimated_delivery_date,actual_delivery_time,estimated_delivery_time,delay,customer_unique_id,customer_zip_code_prefix,customer_city,customer_state,payment_sequential,payment_type,payment_installments,payment_value,order_item_id,shipping_limit_date,price,freight_value,product_name_lenght,product_description_lenght,product_photos_qty,product_weight_g,product_length_cm,product_height_cm,product_width_cm,seller_zip_code_prefix,seller_city,seller_state,product_category_name_english
0,eletrodomesticos,131fcb0a0c9a47bba4474aacff0f14b7,4d071a22b9cc548b64a75075a4c63151,5561adcb0fd46da4cad3048fa4e7fc00,819b0aa9b717f6d78c0f72211bafebe3,delivered,2018-06-25,2018-06-25 15:58:17,2018-06-26 14:58:00,2018-06-27,2018-07-11,2.0,16,-14.0,87d406e4698a66118241f1f4a407ee03,04216,sao paulo,SP,1,credit_card,1,109.35,1,2018-07-02 15:58:17,99.90,9.45,35,342,3,750,22,7,22,01201,sao paulo,SP,home_appliances
1,beleza_saude,e9779976487b77c6d4ac45f75ec7afe9,55945cf4a4e6def88dcc8996a581608a,db5fdbee9ab29d55f24c329246e6fe51,3487bedbddf4797d7308d0aa43dcf30b,delivered,2017-06-17,2017-06-17 13:25:13,2017-06-19 12:49:33,2017-06-26,2017-07-11,9.0,24,-15.0,9949e007c1f037474a3423372cccb701,23832,itaguai,RJ,1,credit_card,3,104.37,1,2017-06-22 13:25:13,89.00,15.37,58,3930,9,275,28,12,22,11701,praia grande,SP,health_beauty
2,esporte_lazer,d05ae8f7a5bd1d2a690a44cd079e4e27,9d8a0e115e802d845b4ce1eb794d1260,6de3383be650cfe96aed26171ad65c47,cae5d18352d2eb7396bd594c706f3624,delivered,2017-10-18,2017-10-18 16:56:50,2017-10-19 22:14:05,2017-10-27,2017-11-06,9.0,19,-10.0,b8baa482e2e3b439ab972fba47c9be48,12080,taubate,SP,1,credit_card,5,355.77,1,2017-10-24 16:56:50,120.00,7.94,30,2299,1,150,20,10,15,22775,rio de janeiro,RJ,sports_leisure
3,brinquedos,de23c3b98a88888289c6f5cc1209054a,9036be77e0a74cca6eeef0740649b97b,9472d3c8a0ad463cbfc89897334431da,7e016f9ea275279784f42e0642214284,delivered,2017-11-20,2017-11-21 09:50:30,2017-11-22 19:48:47,2017-12-21,2017-12-12,31.0,22,9.0,646d643b4ac1184e383341f8896c3dc8,60764,fortaleza,CE,1,credit_card,2,20.03,1,2017-11-27 09:50:30,69.99,19.03,57,697,3,405,21,7,15,05530,sao paulo,SP,toys
4,esporte_lazer,87142160b41353c4e5fca2360caf6f92,3a05a947f28cf46d789adedc107d7595,fa859e78da068661b096bfb4466ded18,065415930d45ace4ad39039b5d0d9341,delivered,2017-12-09,2017-12-11 17:11:20,2017-12-13 20:16:26,2017-12-19,2018-01-18,10.0,40,-30.0,5533b6863859076febafeed9a35bb6c2,18570,conchas,SP,1,credit_card,2,145.58,1,2017-12-19 17:11:20,119.90,25.68,57,652,1,3450,16,15,20,90230,porto alegre,RS,sports_leisure

In [6]:
df.columns

Index(['product_category_name', 'seller_id', 'product_id', 'order_id',
       'customer_id', 'order_status', 'order_purchase_timestamp',
       'order_approved_at', 'order_delivered_carrier_date',
       'order_delivered_customer_date', 'order_estimated_delivery_date',
       'actual_delivery_time', 'estimated_delivery_time', 'delay',
       'customer_unique_id', 'customer_zip_code_prefix', 'customer_city',
       'customer_state', 'payment_sequential', 'payment_type',
       'payment_installments', 'payment_value', 'order_item_id',
       'shipping_limit_date', 'price', 'freight_value', 'product_name_lenght',
       'product_description_lenght', 'product_photos_qty', 'product_weight_g',
       'product_length_cm', 'product_height_cm', 'product_width_cm',
       'seller_zip_code_prefix', 'seller_city', 'seller_state',
       'product_category_name_english'],
      dtype='object')

In [7]:
df.describe()

       actual_delivery_time  estimated_delivery_time          delay
count         115030.000000            115038.000000  115030.000000
mean              12.423620                24.464586     -12.040963
std                9.464209                 8.813719      10.163258
min                0.000000                 3.000000    -147.000000
25%                7.000000                19.000000     -17.000000
50%               10.000000                24.000000     -13.000000
75%               16.000000                29.000000      -7.000000
max              210.000000               156.000000     188.000000

In [8]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 115038 entries, 0 to 115037
Data columns (total 37 columns):
 #   Column                         Non-Null Count   Dtype
---  ------                         --------------   -----
 0   product_category_name          113410 non-null  object
 1   seller_id                      115038 non-null  object
 2   product_id                     115038 non-null  object
 3   order_id                       115038 non-null  object
 4   customer_id                    115038 non-null  object
 5   order_status                   115038 non-null  object
 6   order_purchase_timestamp       115038 non-null  object
 7   order_approved_at              115023 non-null  object
 8   order_delivered_carrier_date   115036 non-null  object
 9   order_delivered_customer_date  115030 non-null  object
 10  order_estimated_delivery_date  115038 non-null  object
 11  actual_delivery_time           115030 non-null  float64
 12  estimated_delivery_time        115038 non-null  int32
 13  delay                          115030 non-null  float64
 14  customer_unique_id             115038 non-null  object
 15  customer_zip_code_prefix       115038 non-null  object
 16  customer_city                  115038 non-null  object
 17  customer_state                 115038 non-null  object
 18  payment_sequential             115035 non-null  object
 19  payment_type                   115035 non-null  object
 20  payment_installments           115035 non-null  object
 21  payment_value                  115035 non-null  object
 22  order_item_id                  115038 non-null  object
 23  shipping_limit_date            115038 non-null  object
 24  price                          115038 non-null  object
 25  freight_value                  115038 non-null  object
 26  product_name_lenght            113410 non-null  object
 27  product_description_lenght     113410 non-null  object
 28  product_photos_qty             113410 non-null  object
 29  product_weight_g               115018 non-null  object
 30  product_length_cm              115018 non-null  object
 31  product_height_cm              115018 non-null  object
 32  product_width_cm               115018 non-null  object
 33  seller_zip_code_prefix         115038 non-null  object
 34  seller_city                    115038 non-null  object
 35  seller_state                   115038 non-null  object
 36  product_category_name_english  113387 non-null  object
dtypes: float64(2), int32(1), object(34)
memory usage: 32.0+ MB

In [9]:
df.isna().sum()

product_category_name            1628
seller_id                           0
product_id                          0
order_id                            0
customer_id                         0
order_status                        0
order_purchase_timestamp            0
order_approved_at                  15
order_delivered_carrier_date        2
order_delivered_customer_date       8
order_estimated_delivery_date       0
actual_delivery_time                8
estimated_delivery_time             0
delay                               8
customer_unique_id                  0
customer_zip_code_prefix            0
customer_city                       0
customer_state                      0
payment_sequential                  3
payment_type                        3
payment_installments                3
payment_value                       3
order_item_id                       0
shipping_limit_date                 0
price                               0
freight_value                       0
product_name_lenght              1628
product_description_lenght       1628
product_photos_qty               1628
product_weight_g                   20
product_length_cm                  20
product_height_cm                  20
product_width_cm                   20
seller_zip_code_prefix              0
seller_city                         0
seller_state                        0
product_category_name_english    1651
dtype: int64

In [10]:
df.nunique()

product_category_name               73
seller_id                         2970
product_id                       32216
order_id                         96478
customer_id                      96478
order_status                         1
order_purchase_timestamp           612
order_approved_at                88274
order_delivered_carrier_date     80106
order_delivered_customer_date      645
order_estimated_delivery_date      445
actual_delivery_time               144
estimated_delivery_time            100
delay                              198
customer_unique_id               93358
customer_zip_code_prefix         14889
customer_city                     4085
customer_state                      27
payment_sequential                  26
payment_type                         4
payment_installments                24
payment_value                    28547
order_item_id                       21
shipping_limit_date              91344
price                             5859
freight_value                     6924
product_name_lenght                 65
product_description_lenght        2944
product_photos_qty                  19
product_weight_g                  2171
product_length_cm                   99
product_height_cm                  102
product_width_cm                    94
seller_zip_code_prefix            2168
seller_city                        595
seller_state                        22
product_category_name_english       71
dtype: int64

In [11]:
df = df.dropna()
df.isna().sum().sum()

np.int64(0)

In [12]:
df.shape

(113360, 37)

In [13]:
df['Delay'] = (df['delay'] > 0).astype(int)

In [14]:
df_final = df[['product_category_name_english', 'customer_state', 'payment_type', 'price', 'freight_value', 'product_weight_g', 'product_length_cm', 'product_height_cm', 'product_width_cm', 'seller_state', 'estimated_delivery_time', 'Delay']]

In [15]:
df_final.info()

<class 'pandas.core.frame.DataFrame'>
Index: 113360 entries, 0 to 115037
Data columns (total 12 columns):
 #   Column                         Non-Null Count   Dtype
---  ------                         --------------   -----
 0   product_category_name_english  113360 non-null  object
 1   customer_state                 113360 non-null  object
 2   payment_type                   113360 non-null  object
 3   price                          113360 non-null  object
 4   freight_value                  113360 non-null  object
 5   product_weight_g               113360 non-null  object
 6   product_length_cm              113360 non-null  object
 7   product_height_cm              113360 non-null  object
 8   product_width_cm               113360 non-null  object
 9   seller_state                   113360 non-null  object
 10  estimated_delivery_time        113360 non-null  int32
 11  Delay                          113360 non-null  int64
dtypes: int32(1), int64(1), object(10)
memory usage: 10.8+ MB

In [16]:
cols_to_float = [
    "price",
    "freight_value",
    "product_weight_g",
    "product_length_cm",
    "product_height_cm",
    "product_width_cm",
    "estimated_delivery_time"
]

df_final[cols_to_float] = df_final[cols_to_float].astype(float)

/tmp/ipykernel_12474/1868742058.py:11: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df_final[cols_to_float] = df_final[cols_to_float].astype(float)

In [17]:
# %pip install scikit-learn

In [18]:
from sklearn.preprocessing import LabelEncoder

cat_cols = [
    "customer_state",
    "seller_state",
    "product_category_name_english",
    "payment_type"
]

le = LabelEncoder()
for col in cat_cols:
    df_final[col] = le.fit_transform(df_final[col].astype(str))

/tmp/ipykernel_12474/2417839983.py:12: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df_final[col] = le.fit_transform(df_final[col].astype(str))
/tmp/ipykernel_12474/2417839983.py:12: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df_final[col] = le.fit_transform(df_final[col].astype(str))
/tmp/ipykernel_12474/2417839983.py:12: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df_final[col] = le.fit_transform(df_final[col].astype(str))
/tmp/ipykernel_12474/2417839983.py:12: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df_final[col] = le.fit_transform(df_final[col].astype(str))

In [19]:
df_final.head()

,product_category_name_english,customer_state,payment_type,price,freight_value,product_weight_g,product_length_cm,product_height_cm,product_width_cm,seller_state,estimated_delivery_time,Delay
0,44,25,1,99.90,9.45,750.0,22.0,7.0,22.0,21,16.0,0
1,43,18,1,89.00,15.37,275.0,28.0,12.0,22.0,21,24.0,0
2,65,25,1,120.00,7.94,150.0,20.0,10.0,15.0,15,19.0,0
3,69,5,1,69.99,19.03,405.0,21.0,7.0,15.0,21,22.0,1
4,65,25,1,119.90,25.68,3450.0,16.0,15.0,20.0,18,40.0,0

In [20]:
neg = (df_final["Delay"] == 0).sum()
pos = (df_final["Delay"] == 1).sum()

scale_pos_weight = neg / pos
scale_pos_weight

np.float64(14.306508236564948)

In [21]:
X = df_final.drop(columns=["Delay"])
y = df_final["Delay"]

In [22]:
from sklearn.model_selection import train_test_split

X_train, X_test, y_train, y_test = train_test_split(
    X, y, test_size=0.2, random_state=42, stratify=y
)

In [25]:
# %pip install xgboost

In [26]:
from xgboost import XGBClassifier

model = XGBClassifier(
    n_estimators=300,
    max_depth=6,
    learning_rate=0.05,
    subsample=0.8,
    colsample_bytree=0.8,
    scale_pos_weight=scale_pos_weight,
    eval_metric="logloss",
    random_state=42
)

In [28]:
model.fit(X_train, y_train)

XGBClassifier(base_score=None, booster=None, callbacks=None,
              colsample_bylevel=None, colsample_bynode=None,
              colsample_bytree=0.8, device=None, early_stopping_rounds=None,
              enable_categorical=False, eval_metric='logloss',
              feature_types=None, feature_weights=None, gamma=None,
              grow_policy=None, importance_type=None,
              interaction_constraints=None, learning_rate=0.05, max_bin=None,
              max_cat_threshold=None, max_cat_to_onehot=None,
              max_delta_step=None, max_depth=6, max_leaves=None,
              min_child_weight=None, missing=nan, monotone_constraints=None,
              multi_strategy=None, n_estimators=300, n_jobs=None,
              num_parallel_tree=None, ...)

In [29]:
y_pred = model.predict(X_test)
y_prob = model.predict_proba(X_test)[:, 1]

In [30]:
from sklearn.metrics import classification_report, roc_auc_score, average_precision_score

print(classification_report(y_test, y_pred))
print("ROC AUC:", roc_auc_score(y_test, y_prob))
print("PR AUC:", average_precision_score(y_test, y_prob))

              precision    recall  f1-score   support

           0       0.97      0.75      0.84     21191
           1       0.15      0.62      0.24      1481

    accuracy                           0.74     22672
   macro avg       0.56      0.69      0.54     22672
weighted avg       0.91      0.74      0.80     22672

ROC AUC: 0.750729745862134
PR AUC: 0.20840951236956015

In [31]:
feat_imp = pd.Series(
    model.feature_importances_,
    index=X.columns
).sort_values(ascending=False)

feat_imp

customer_state                   0.183468
estimated_delivery_time          0.132564
seller_state                     0.103167
freight_value                    0.092560
product_weight_g                 0.075575
price                            0.074866
payment_type                     0.069583
product_height_cm                0.068367
product_length_cm                0.068012
product_width_cm                 0.066102
product_category_name_english    0.065734
dtype: float32